### ISSUE TITLE
Warning message: In if (n != 3) return(expr) :   the condition has length > 1 and only the first element will be used

### ISSUE THREAD

**Issue by MatthieuStigler** [DavisVaughan/furrr#115]
I get a warning messge: *Warning message: In if (n != 3) return(expr) :   the condition has length > 1 and only the first element will be used*. 

This happens when the input to `future_map` is a `Formula` object (from package Formula). Any idea what is going on wrong here?

Thanks!!

``` r
library(furrr)
#> Loading required package: future

packageVersion("furrr")
#> [1] '0.1.0.9002'
packageVersion("future")
#> [1] '1.18.0'

fi <- list(f1 = Formula::Formula(Sepal.Length~Sepal.Width))
fi2 <- list(f1 = Sepal.Length~Sepal.Width)

future_map(fi2, ~lm(., data= iris))
#> $f1
#> 
#> Call:
#> lm(formula = ., data = iris)
#> 
#> Coefficients:
#> (Intercept)  Sepal.Width  
#>      6.5262      -0.2234
future_map(fi, ~lm(., data= iris))
#> Warning in if (n != 3) return(expr): the condition has length > 1 and only the
#> first element will be used
#> $f1
#> 
#> Call:
#> lm(formula = ., data = iris)
#> 
#> Coefficients:
#> (Intercept)  Sepal.Width  
#>      6.5262      -0.2234
```

<sup>Created on 2020-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
This warning is due to the very unfortunate fact that Formula formulas return a result from `length()` that isn't length 1.

``` r
fi <- Formula::Formula(Sepal.Length~Sepal.Width)

length(fi)
#> [1] 1 1

Formula:::length.Formula
#> function (x) 
#> {
#>     c(length(attr(x, "lhs")), length(attr(x, "rhs")))
#> }
#> <bytecode: 0x7fd7a3b1fba0>
#> <environment: namespace:Formula>
```

<sup>Created on 2020-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

There is nothing that I can do about this in furrr, so I am going to close this.

@HenrikBengtsson, if you want to handle this specific case in future, it comes from `future:::tweakFutureAssignmentCall()` making the perfectly reasonable assumption that `length()` returns something of length 1.

``` r
fi <- Formula::Formula(Sepal.Length~Sepal.Width)

# Comes from here...
gp <- future::getGlobalsAndPackages(fi)
#> Warning in if (n != 3) return(expr): the condition has length > 1 and only the
#> first element will be used

# Which calls this:
globals:::findGlobals(fi, tweak = future:::tweakExpression)
#> Warning in if (n != 3) return(expr): the condition has length > 1 and only the
#> first element will be used
#> [1] "~"            "Sepal.Length" "Sepal.Width"

# tweakExpression() uses tweakFutureAssignmentCall() which makes the
# perfectly reasonable assumption that `length(expr)` returns
# something of length 1
future:::tweakFutureAssignmentCall(fi)
#> Warning in if (n != 3) return(expr): the condition has length > 1 and only the
#> first element will be used
#> Sepal.Length ~ Sepal.Width
```

<sup>Created on 2020-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by HenrikBengtsson** [comment]
Thanks to OP for reporting and thanks to Davis for troubleshooting.  Yeah, it's an odd use of `length()` going on there in {Formula].  I suppose it needs to be fixed because right now the outcome with futures is unknown (at least to me).  I'm now tracking this in https://github.com/HenrikBengtsson/future/issues/395.
