### ISSUE TITLE
Automatically set plan() based on OS

### ISSUE THREAD

**Issue by timvink** [DavisVaughan/furrr#17]
Awesome package, thanks for this! I would like to implement it in an internal package at work. Problem is some users are on mac, while others are on windows. 

From the README: 

> \# You set a "plan" for how the code should run. The easiest is `multiprocess`
> \# On Mac this picks plan(multicore) and on Windows this picks plan(multisession)
> plan(multiprocess)

Is there reason you do not auto-detect the OS and set the `plan()` accordingly? 
And if this 'auto-detect' is something that you do not want by default, we would perhaps expand  `furrr::future_options()` so you could do something like :

```r
future_map(c(2, 2, 2), ~Sys.sleep(.x), .options = future_options(plan = "auto-detect")
```

If you agree this is something that could be improved, I'd be happy to give it a try and make a pull request :)

**Comment by DavisVaughan** [comment]
This is actually something that `future` strongly advocates against! These future style functions should let the _user_ decide where the code is executed (the plan), and the _developer_ worries about the code that is executed.

The reason why what you are saying would not work is because it just covers working with Mac vs windows. You can also use this package to run code in parallel on clusters that might be on completely different machines, among other things. That wouldn't work with an auto plan

**Comment by timvink** [comment]
Ok fair point, thanks for explaining! Going to implement the furrr functions and lets my users know how to optionally set `plan()` to speed things up.
