### ISSUE TITLE
Tidyverse integration or keep seperate

### ISSUE THREAD

**Issue by instantkaffee** [DavisVaughan/furrr#2]
Thanks for the package.
This addresses the long-term wish for parallel purrr.
See https://github.com/tidyverse/purrr/issues/121.

Questions:

- Are you in touch with the tidyverse stakeholder (i.e. https://github.com/hadley, https://github.com/lionel-)?

- I wonder if/how your package will be integrated to the official tidyverse stack.
Any thougths?

**Comment by DavisVaughan** [comment]
I am not directly in touch with them about this, but it is heavily rumored that they are working on it as well. I doubt this package will be integrated, as their approach may or may not use the future package, and might be more tightly coupled with the C code in purrr. Even so, furrr will not be completely useless if they have parallel purrr because of the ability to use it with future.batchtools across multiple computers, which I am not sure that the tidyverse purrr will support. 

furrr is really just my attempt to give the community something they have been asking for for awhile as a temporary solution until an official solution can come out.
