### ISSUE TITLE
Setting `seed = TRUE` / `.progress=TRUE` globally in the R session

### ISSUE THREAD

**Issue by elgabbas** [DavisVaughan/furrr#254]
Hello,

I would like to use the `furrr::furrr_options(seed = TRUE)` option in multiple `furrr` functions in the same session. Is it possible to set `seed = T` once per session, not to add it repeatedly as `.options` argument of furrr functions (e.g. `furrr::future_map`).

Similarly, is it possible to set `.progress=TRUE` globally in the session?

Cheers, Ahmed

**Comment by DavisVaughan** [comment]
No, and I don't believe that global options like this are great practice. You might end up calling someone else's function that also uses furrr, and your global option could interact with their `future_map()` calls in ways that you didn't expect (because you might not have even known they were using `future_map()`)
