### ISSUE TITLE
Custom methods are invisible for workers in PSOCK cluster

### ISSUE THREAD

**Issue by statist-bhfz** [DavisVaughan/furrr#50]
I have an issue when creating PSOCK cluster on Windows machine:
```
library(furrr)
cl <- parallel::makePSOCKcluster(3)
plan(cluster, workers = cl)
future_map_dfr(...)
```
It works great until I pass to `future_map_dfr` function which use custom methods for `predict` (`perdict.label_enc` and others). 
The error is
```
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('label_enc', 'data.table', 'data.frame')"
```
These metods are defined in sourced .R file and are visible in global enviromnet. When I call `clusterEvalQ()` with all required `source()` inside and/or `clusterExport()` with all functions names, it has no effect.
`future::makeClusterPSOCK()` and `plan(multiprocess)` give me the same error.

Function example:
```
label_encoder <- function(data, cols) {
    checkmate::assert_data_table(data)
    checkmate::assert_character(cols)
    checkmate::assert_names(names(data), must.include = cols)

    res <- melt(data[, .SD, .SDcols = cols],
                measure.vars = cols, variable.factor = FALSE)
    res <- unique(res)
    res[, number := rowid(variable)]

    class(res) <- c("label_enc", class(res))
    return(res)
}

predict.label_enc <- function(object, newdata, suffix = "_lab", drop = FALSE, ...) {
    checkmate::assert_data_table(newdata)

    cols <- intersect(object[, unique(variable)], names(newdata))
    if (length(cols) == 0L) {
        return(newdata[])
    }
    cols_new <- paste0(cols, suffix)
    for (i in seq_along(cols)) {
        newdata[object[variable == cols[i]],
                (cols_new[i]) := number,
                on = paste0(cols[i], "==value")]
    }
    if (drop && nzchar(suffix)) {
        newdata[, (cols) := NULL]
    }

    # return(newdata[])
}
```
So, `label_encoder()` is called first (without an error), but next call is `predict()` for "label_enc" object.

**Comment by DavisVaughan** [comment]
A few things here:

> When I call clusterEvalQ() with all required source() inside and/or clusterExport() with all functions names, it has no effect.

The `future` ecosystem doesn't use `clusterEvalQ()` so these functions won't have any effect.

> `predict.label_enc`

My guess is that because you call the function `predict()` inside `future_map_dfr()`, and not `predict.label_enc()`, the underlying `globals` package does not pick up that you need `predict.label_enc` over on the workers. You could try explicitly passing the function as a global with `future_map_dfr(..., .options = future_options(globals = predict.label_enc))`. That may work.

Alternatively you can directly call `predict.label_enc` rather than `predict` inside the `future_map_dfr` call.

Finally, if you wanted to put that predict method and maybe the `label_encoder` function in a package and then use that inside the `future_map_dfr` call, then just calling `predict` should work

**Comment by statist-bhfz** [comment]
@DavisVaughan Thank you! One more reason to organize my code in package :)
