### ISSUE TITLE
Global option to set .progress

### ISSUE THREAD

**Issue by gadenbuie** [DavisVaughan/furrr#66]
When translating `purrr` to `furrr`, I often want to enable progress bars, but this adds an option to the `future_*()` function call that doesn't exist in the `purrr` version. I tend to go back and forth between implementations to test multiprocess speed-up and while it's easy to simply prepend `future_` I often forget to add or remove the `.progress = TRUE` option. It would be nice to be able to set this via a global option to enable/disable progress bars everywhere, and it would somewhat fit in with the workflow of setting `plan(multiprocess)` after attaching `furrr`.

I may be alone in this and I certainly recognize the low priority of this request vs changing the API, but this would take a bit of friction out of my personal workflow.

**Comment by DavisVaughan** [comment]
I appreciate the interest! I think that a global option is not a bad idea, it is somewhat inline with how readxl decides whether or not to show a progress bar
https://github.com/tidyverse/readxl/blob/9d665bbb46923281911eddd4531617a461bad645/R/progress.R#L6

That said, the progress bar was a somewhat bleeding edge idea, hacked together. I probably shouldn't have included it, if I'm being honest.

`future` has plans to incorporate progress bars more generally into the future framework. Rather than add on to this ad hoc feature, I'd rather bide my time and wait for the more "official" solution, and then work that into furrr. Sound alright?

**Comment by DavisVaughan** [comment]
A bit of work has started towards a more general progress bar framework for futures. I'm going to let this issue die, with hopes to eventually deprecate the `.progress` option of furrr in favor of the more general approach https://github.com/HenrikBengtsson/progressr
