### ISSUE TITLE
future_map fails to identify global variables but map can

### ISSUE THREAD

**Issue by wenjia2018** [DavisVaughan/furrr#75]
Hi, I met a problem when using future_map, it can not identify global objects. I produced a simple example to demonstrate a simplified version of my problem.
is there any solution for this? I am using mac
thanks!!!

library(tidyverse)
library(furrr)
plan(multiprocess, workers = detectCores()/2)
x1=rnorm(100)
x2=rnorm(100,2,4)
data=bind_cols(x1=x1,x2=x2) %>% as.data.frame()
y1=rnorm(100,4,10)
y2=rnorm(100,2,6)
y3=rnorm(100,1,3)
outcomes=list(y1=y1,y2=y2,y3=y3)
arg=expand.grid(
  outcomes = names(outcomes), # toggle jointly with the previous comment
  focal_treatment = c("x1 + x2"),
  stringsAsFactors = F
) %>%
  unite(model_formulae, sep = " ~ ", remove = F)

out_future=future_map(arg$model_formulae,lm)# error Error in eval(predvars, data, env) : #object 'y1' not found
out_map=map(arg$model_formulae,lm)#works

**Comment by DavisVaughan** [comment]
Minimal reprex:

``` r
library(purrr)
library(furrr)
#> Loading required package: future

plan(multisession, workers = 2)

x <- 1
y <- 1
formula_string <- "x ~ y"

future_map(formula_string, lm)
#> Error in eval(predvars, data, env): object 'x' not found

map(formula_string, lm)
#> [[1]]
#> 
#> Call:
#> .f(formula = .x[[i]])
#> 
#> Coefficients:
#> (Intercept)            y  
#>           1           NA
```

<sup>Created on 2019-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
So, all that you are providing `future_map()` with is:
1) a string
2) the `lm()` function

So those are the only two things that get loaded on the workers.

The underlying `globals` package that searches for things to export can't figure out that you really wanted the `x` variable from the `formula_string` in the above example. It works in the `map()` call because `lm()` is special and looks to the surrounding environment when passed a character formula.

My advice is that, if you want to do something like your example, you should really be passing a `data` argument into `lm()`. This is best practice anyways. I probably wouldn't use a string as the formula either. So maybe something like this!

``` r
library(tibble)
library(furrr)
#> Loading required package: future

plan(multiprocess, workers = parallel::detectCores()/2)

predictors <- tibble(
  x1=rnorm(100),
  x2=rnorm(100,2,4)
)

outcomes <- list(
  y1 = rnorm(100,4,10),
  y2 = rnorm(100,2,6),
  y3 = rnorm(100,1,3)
)

future_imap(outcomes, ~{
  lm_data <- cbind(y = .x, predictors)
  lm(y ~ ., data = lm_data)
})
#> $y1
#> 
#> Call:
#> lm(formula = y ~ ., data = lm_data)
#> 
#> Coefficients:
#> (Intercept)           x1           x2  
#>      4.8510       2.6580       0.4333  
#> 
#> 
#> $y2
#> 
#> Call:
#> lm(formula = y ~ ., data = lm_data)
#> 
#> Coefficients:
#> (Intercept)           x1           x2  
#>     2.31648      0.14378     -0.01205  
#> 
#> 
#> $y3
#> 
#> Call:
#> lm(formula = y ~ ., data = lm_data)
#> 
#> Coefficients:
#> (Intercept)           x1           x2  
#>      1.0941       0.1686       0.1745
```

<sup>Created on 2019-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
Otherwise, this isn't really a furrr bug so I'm going to close

**Comment by wenjia2018** [comment]
Thanks a lot, Davis!
