### ISSUE TITLE
group_future_map might be a nice addition.

### ISSUE THREAD

**Issue by Ax3man** [DavisVaughan/furrr#79]

**Comment by wlandau** [comment]
And `future_group_modify()`.

**Comment by DavisVaughan** [comment]
I'm intrigued by this idea but im not sure furrr is the right place since it is so specific to matching the purrr api, and these functions are from dplyr. I also don't want a hard Import dependency on dplyr if I can help it (I could work around it if I had to).

I took a quick look at how it might work, and unfortunately these functions do a bit more than what the purrr `map()` family does, so it's hard to see exactly how I'd add them in. I'll think about this a bit more.

**Comment by jg43b** [comment]
For what it's worth, I think the following pattern more or less captures the intended functionality:
```r
df %>%
  group_by(!!!grouping_cols) %>%
  group_split() %>%
  future_map(func) %>%
  bind_rows()
```
Of course, three function calls is not as clean as one, and I don't know if there's overhead that can be avoided here.

**Comment by DavisVaughan** [comment]
I'm going to try and keep furrr completely aligned with purrr rather than adding in some of the dplyr specific verbs
