### ISSUE TITLE
Rcpp function doesn't work with multiprocess

### ISSUE THREAD

**Issue by aornugent** [DavisVaughan/furrr#82]
Hi, this is driving me a bit mad, but I think I've zeroed in on the culprit. 

An Rcpp function isn't getting evaluated correctly when using `plan(multiprocess)`. Strangely, I think it has worked in a previous iteration so it's unclear to me what has changed:

``` r
library(furrr)
#> Loading required package: future
#> Warning: package 'future' was built under R version 3.5.3
library(Rcpp)
#> Warning: package 'Rcpp' was built under R version 3.5.3
library(RcppArmadillo)
#> Warning: package 'RcppArmadillo' was built under R version 3.5.2
library(inline)
#> 
#> Attaching package: 'inline'
#> The following object is masked from 'package:Rcpp':
#> 
#>     registerPlugin

# Fast sampling from multivariate distribution
rmvnorm <- inline::cxxfunction(
  signature(n_="integer", mu_="numeric", sigma_="matrix"),
  'using namespace Rcpp;
    int n = as<int>(n_);
    arma::vec mu = as<arma::vec>(mu_);
    arma::mat sigma = as<arma::mat>(sigma_);
    int ncols = sigma.n_cols;
    arma::mat Y = arma::randn(n, ncols);
    return wrap(arma::repmat(mu, 1, n).t() + Y * arma::chol(sigma));',
  plugin="RcppArmadillo", verbose=F)

# Works
plan(sequential)
future_map(1, ~ rmvnorm(1, c(0, 0), matrix(c(1, 0.2, 0.2, 1), ncol = 2)))
#> Warning: package 'purrr' was built under R version 3.5.3
#> [[1]]
#>           [,1]     [,2]
#> [1,] 0.8574415 1.115667

# Doesn't work
plan(multiprocess)
future_map(1, ~ rmvnorm(1, c(0, 0), matrix(c(1, 0.2, 0.2, 1), ncol = 2)))
#> Error in .Primitive(".Call")(<pointer: (nil)>, n_, mu_, sigma_): NULL value passed as symbol address
```

<sup>Created on 2019-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
This falls under the section of Non Exportable Object in the future framework. See this vignette and search for "Rcpp"
https://cran.r-project.org/web/packages/future/vignettes/future-4-non-exportable-objects.html

Are you on a mac and do you work in rstudio? This may have worked in a previous version of future, where `multiprocess` meant `multicore` on a mac. In the current version, when you set `multiprocess` on a mac while in rstudio, it changes to `multisession` for robustness rather than `multicore`. There is a chance it may have worked before with `multicore` because you'd be able to share memory rather than have to copy objects from one session to another (which is where it breaks).

**Comment by aornugent** [comment]
That explains it, thank you.
