### ISSUE TITLE
furrr is very magical

### ISSUE THREAD

**Issue by hadley** [DavisVaughan/furrr#9]
e.g. https://github.com/DavisVaughan/furrr/blob/master/R/future_map2_template.R

I think you should consider an interface where the user has more control over exactly what is sent to the various backends, and then build a more magical interface on top of that.

You could imagine maybe something like this:

```R
backend <- furrr_backend()
backend$load_packages("purrr")

x <- runif(1e6)
backend$copy_data(x)
backend$run_code(y <- runif(1))

future_map(1:5, ~ .x + y, backend = backend)
```

**Comment by DavisVaughan** [comment]
I think part of the magic of `future` is that it magically finds relevant variables/packages through the `globals` package. Right now that can be explicitly controlled with the `future.globals` and `future.packages` arguments if something is being skipped. I kind of liked that because it became nearly a drop in replacement, but there is some performance loss from looking things up. 

Are you suggesting only objects in `backend` would be exported? Or did "and then build a more magical interface on top of that" mean that we could try and auto lookup anything not included in `backend`?

Would you imagine `backend$load_packages("purrr")` executing immediately on each worker, or being built up into some kind of list of expressions to execute all at once when `future_map()` is finally called? If the former, I have to figure out how to get a `future` backend to "stick around" as an object in the master R process. 

Right now:
- When `plan(multicore)` is called, nothing really happens until `future_map()` is called, where the processes open, run the code, and shut down immediately.
- When `plan(multisession)` is called, R processes open immediately, and stick around for multiple `future_map()` calls until a new plan is set or the master process is shut down. But I still don't know how to access the cluster object that get's created.

I'm sure there's a way, just haven't done enough digging.

**Comment by DavisVaughan** [comment]
I'm now happy with how #8 has been implemented, and sadly we can't always access the explicit backend and keep it around persistently.
