### ISSUE TITLE
future_map_dfr fails when scheduled and called in a function 

### ISSUE THREAD

**Issue by BChukwuSmith** [DavisVaughan/furrr#91]
I am currently using map_dfr on a jsonlite::fromJSON command.  I was able to run my script from the Rstudio IDE, from the command line, and scheduling a cron job that runs the API alone by itself.

However, when I put the API call inside a function to call from future_map_dfr, it failed, but the same call was successful with just map_dfr.  

Any insights about this issue would be helpful.

**Comment by DavisVaughan** [comment]
Without a reproducible example, unfortunately I won't be able to help very much. What you are describing works for me. Since this has been open for awhile, I'm going to close, but please open a new issue if you can provide a reproducible example

``` r
library(purrr)
library(furrr)
#> Loading required package: future
plan(multisession)

map_dfr(1:2, ~data.frame(x = jsonlite::fromJSON("[1]")))
#>   x
#> 1 1
#> 2 1
future_map_dfr(1:2, ~data.frame(x = jsonlite::fromJSON("[1]")))
#>   x
#> 1 1
#> 2 1
```

<sup>Created on 2020-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
