### ISSUE TITLE
Issues with devtools::load_all()

### ISSUE THREAD

**Issue by GShotwell** [DavisVaughan/furrr#95]
It seems like when you use furrr as part of a package development process you need to reinstall the package to pass the right functions down  to the workers. I've set up an example package to demonstrate this  behaviour, as a user my expectation is that the version of the function passed to the worker is the same one that I have  loaded after running `devtools::load_all()`

https://github.com/GShotwell/furrr_bug/blob/bug_report/vignettes/bug.Rmd

Thanks for the great package!

**Comment by soetang** [comment]
Yes, i experience the same.

Functions loaded with devtools::load_all(), seems not to passed to furrr (external pointer error).

devtools::install, is required. A fix would be nice - since this makes package development more cumbersome. However, i am not sure a fix is possible given how devtools::load_all() works?

**Comment by crotman** [comment]
I think that it would be great if this issue was in the documentation. I lost an entire day until I find this issue here. Thanks for this excellent package!

**Comment by DavisVaughan** [comment]
I'm fairly certain what happens here is that the underlying globals package sees that the function you are trying to export comes from a package namespace, so it doesn't try and export it. Instead it would in theory try and load up that package on the worker. But the package isn't installed, so it will fail. There isn't anything that I can do about this in furrr, and I doubt that this can really be changed in globals. I'll add some documentation though.

**Comment by GShotwell** [comment]
Thanks for the documentation, is it worth adding a warning if devtools::load_all() has been called prior to the parallel processing? This could be triggered with:
```
if ("devtools_shims" %in% search()) {
    warning("..."
}
```
It's probably possible, but likely not worth it, to inspect the functions and see which are loaded by devtools.

**Comment by DSChip** [comment]
I have a very similar issue.

I'm working on a custom package, where I have developed a set of similar functions, let's say `ingest_*_batch()`.
I have run: `devtools::document()` followed by `devtools::load_all()` followed by RStudio IDE "Clean & Install".

I'm using  `furrr::future_pmap()`  to parallelize my function. E.g.,
```furrr::future_pmap(~ingest_foo_batch(.x), .progress = TRUE, .options = furrr::furrr_options(packages = "myPackage"))```
and excluding the `.options` argument
```furrr::future_pmap(~ingest_foo_batch(.x), .progress = TRUE)```

I have the main function `ingest_main_batch()` fully documented using roxygen2 comments.
For, the other set of functions, I've used `#' @describeIn ingest_main_batch ...`.

Whenever I use `#' @describeIn ...`, I'm presented with two outcomes:
- `future::plan(sequential)`: It always works.
- `future::plan(multisession)`: `furrr::future_pmap()` fails to detect my function.

If, instead of using `#' @describeIn ...` I write full documentation for all related functions, it works both in sequential and parallel.
This makes me thing that there's an issue triggered by `#' @describeIn`.

**Does anybody know what could be the issue?**
**Is there any change that I need to include in my roxygen2 documentation for this to work?**
