### ISSUE TITLE
Should progress bars print to `cat()`?

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/furrr#97]
They are quite hard to suppress, see #96 

Should it be message()? Investigate other packages like `progress`
https://github.com/r-lib/progress/blob/b146a6a74d14c1cf4a3689ae745a0c0f38a355d2/R/progress.R#L508

**Comment by HenrikBengtsson** [comment]
I know this one is moot, but, yes, first, you definitely want to output to stderr, and, second, using 'message' conditions is much neater because they can be "captured" via condition handlers.  Capturing stderr in R is broken, cf. https://github.com/HenrikBengtsson/Wishlist-for-R/issues/55.  The 'progress' package uses 'message' conditions.

**Comment by DavisVaughan** [comment]
I'll be nuking the `.progress` option in favor of progressr, so this won't matter
